version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  test-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123


  redis:
    image: 'redis:latest'
    container_name: microservice-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL'
    labels:
      kompose.service.type: nodeport
    command:
      - redis-server
      - '--bind'
      - redis
      - '--port'
      - '6379'
    volumes:
      - 'redis_data:/usr/local/etc/redis/redis.conf'
    ports:
      - '6379:6379'
    networks:
      - redis-net